import Navbar from "@/components/Navbar/Navbar";
import { ThemeProvider } from "@/components/Themes/theme-provider";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Poppins } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cadeau Anais",
  description: "Generated by Lespacito",
};

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={poppins.className}>
        <Suspense fallback={<div>Chargement...</div>}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider>
              <Navbar />
              {children}
              <Toaster position="top-right" richColors />
            </SessionProvider>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
